"""change security_events.event_type to enum

Revision ID: 8e80eff20be9
Revises: eeedcf2c1589
Create Date: 2026-10-03 13:09:54.440930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e80eff20be9'
down_revision: Union[str, Sequence[str], None] = 'eeedcf2c1589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_events', 'event_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILED', 'SUSPICIOUS_LOGIN', 'ACCOUNT_LOCKED', 'RATE_LIMIT_EXCEEDED', 'PASSWORD_CHANGED', 'PASSWORD_RESET', 'SESSION_CREATED', 'SESSION_REVOKED', 'ALL_SESSIONS_REVOKED', name='security_event_type', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('security_events', 'event_type',
               existing_type=sa.Enum('LOGIN_SUCCESS', 'LOGIN_FAILED', 'SUSPICIOUS_LOGIN', 'ACCOUNT_LOCKED', 'RATE_LIMIT_EXCEEDED', 'PASSWORD_CHANGED', 'PASSWORD_RESET', 'SESSION_CREATED', 'SESSION_REVOKED', 'ALL_SESSIONS_REVOKED', name='security_event_type', native_enum=False),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
