"""feat: add new column

Revision ID: e6ebb133a8f0
Revises: 5621af163af6
Create Date: 2026-09-15 13:09:31.439412

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6ebb133a8f0"
down_revision: Union[str, Sequence[str], None] = "5621af163af6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "role_permissions", sa.Column("organization_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "role_permissions",
        "organizations",
        ["organization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "role_permissions", type_="foreignkey")
    op.drop_column("role_permissions", "organization_id")
    # ### end Alembic commands ###
